// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// In static hosting (e.g., GitHub Pages), env vars might be missing at runtime if not embedded at build time.
// To avoid crashing the entire app on initial load, export a safe fallback that throws only when used.
let client: ReturnType<typeof createClient<Database>> | { functions: { invoke: (...args: any[]) => Promise<never> } };

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('[Supabase] Configuration Error:');
  console.error('  VITE_SUPABASE_URL:', SUPABASE_URL ? '✓ Set' : '✗ Missing');
  console.error('  VITE_SUPABASE_PUBLISHABLE_KEY:', SUPABASE_PUBLISHABLE_KEY ? '✓ Set' : '✗ Missing');
  console.error('  Please set these environment variables in your .env file and rebuild the application.');

  client = {
    functions: {
      async invoke() {
        throw new Error('Supabase is not configured. Please check the browser console for details and contact the site administrator.');
      },
    },
  } as any;
} else {
  console.log('[Supabase] Successfully initialized');
  console.log('  Project URL:', SUPABASE_URL);

  client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

export const supabase = client;